### PR TITLE
Jspss93094 hw4 attempt1

### PR DESCRIPTION
**Pull request by jspss93094**
---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

### CODE REVIEW

**Comment by tigercosmos** [comment]
why you have so many commits???

**Comment by jspss93094** [comment]
@tigercosmos  It can pass in my computer, but can not pass the CI. So, I tried many times to find the reason.

**Comment by tigercosmos** [comment]
no I mean there are some irrelevant commits. (such as HW01, HW02)
You will want to squash your commits if you are making PR in the real open source projects.
It's fine for NSD.

**Comment by jspss93094** [comment]
@tigercosmos Sorry. Maybe I did in mistake, but I did not know. I just fetch the upstream and merge to the new branch, but that new branch is create from hw4. And then I update it to the github. How should I fetch the upstream and to what branch？ Thanks.

**Comment by jspss93094** [comment]
Maybe you mean I can use rebase to squash that too many commits？

**Comment by tigercosmos** [comment]
You may do something wrong on Git.
Just remind you it's better to rebase and squash if you are contributing to open source projects.

**Pull request merged**
